development:
adapter: postgresql
encoding: unicode
database: meric
pool: 5
timeout: 5000

test:
adapter: postgresql
database: postgres
pool: 5
timeout: 5000

production:
adapter: postgresql
database: ENV['DATABASE_URL']
pool: 5
timeout: 5000
