
source 'https://rubygems.org'
gem 'addressable'
ruby '2.4.1'
gem 'dotenv'
gem 'facebook-messenger', github: 'hyperoslo/facebook-messenger'
gem 'httparty'
gem 'puma'
gem 'sinatra'
gem 'giphy'
gem 'activerecord'
gem 'sinatra-activerecord' # excellent gem that ports ActiveRecord for Sinatra
gem 'activesupport'
gem 'pg'
gem 'rake'
gem 'ocr_space'
